"""ondelete cascade on users

Revision ID: 056741f0eee8
Revises: fd56dd908eba
Create Date: 2026-04-28 13:49:29.636470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056741f0eee8'
down_revision: Union[str, Sequence[str], None] = 'fd56dd908eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workspace_owner_id_fkey'), 'workspace', type_='foreignkey')
    op.create_foreign_key(None, 'workspace', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_owner_id_fkey'), 'workspace', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
