"""add pydantic_ai_message column

Revision ID: 06efe6b12cfc
Revises: 3581b140f816
Create Date: 2026-05-18 01:44:13.906134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06efe6b12cfc'
down_revision: Union[str, Sequence[str], None] = '3581b140f816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('pydantic_ai_message', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'pydantic_ai_message')
    # ### end Alembic commands ###
