"""remove unique constraints

Revision ID: 290f3ec0038a
Revises: cee2ed1feb21
Create Date: 2026-06-13 11:21:39.729261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290f3ec0038a'
down_revision: Union[str, Sequence[str], None] = 'cee2ed1feb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_chat_document'), 'chats', type_='unique')
    op.drop_constraint(op.f('uq_workspace_document'), 'chats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_workspace_document'), 'chats', ['workspace_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_chat_document'), 'chats', ['document_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
