"""workspace_id nullable in docs

Revision ID: 38d4b52b4e95
Revises: 1ed025f7ecb5
Create Date: 2026-06-07 10:33:43.747633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d4b52b4e95'
down_revision: Union[str, Sequence[str], None] = '1ed025f7ecb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
