"""remove slug from workspace

Revision ID: 3f474a039148
Revises: b15fe0b87587
Create Date: 2026-04-19 08:23:44.369218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f474a039148'
down_revision: Union[str, Sequence[str], None] = 'b15fe0b87587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_slug'), table_name='workspace')
    op.drop_column('workspace', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_workspace_slug'), 'workspace', ['slug'], unique=True)
    # ### end Alembic commands ###
