"""removed workspaces chats have 1 to many with docs

Revision ID: 6f9946ff7426
Revises: 290f3ec0038a
Create Date: 2026-06-25 18:13:30.696643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f9946ff7426'
down_revision: Union[str, Sequence[str], None] = '290f3ec0038a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_workspace_owner_id'), table_name='workspace')
    #op.drop_table('workspace')
    op.drop_index(op.f('ix_chats_document_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_workspace_id'), table_name='chats')
    #op.drop_constraint(op.f('chats_workspace_id_fkey'), 'chats', type_='foreignkey')
    #op.drop_constraint(op.f('chats_document_id_fkey'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'document_id')
    op.drop_column('chats', 'workspace_id')
    op.add_column('documents', sa.Column('chat_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'chat_id')
    op.add_column('chats', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chats_document_id_fkey'), 'chats', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('chats_workspace_id_fkey'), 'chats', 'workspace', ['workspace_id'], ['id'])
    op.create_index(op.f('ix_chats_workspace_id'), 'chats', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_chats_document_id'), 'chats', ['document_id'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_quota_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_personal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('workspace_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_pkey'))
    )
    op.create_index(op.f('ix_workspace_owner_id'), 'workspace', ['owner_id'], unique=False)
    # ### end Alembic commands ###
