"""add workspace_id to chats

Revision ID: 8caf957f0f56
Revises: b634daa22221
Create Date: 2026-05-31 18:16:19.152887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caf957f0f56'
down_revision: Union[str, Sequence[str], None] = 'b634daa22221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.alter_column('chats', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_chats_workspace_id'), 'chats', ['workspace_id'], unique=False)
    op.create_unique_constraint('uq_workspace_document', 'chats', ['workspace_id'])
    op.create_foreign_key(None, 'chats', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint('uq_workspace_document', 'chats', type_='unique')
    op.drop_index(op.f('ix_chats_workspace_id'), table_name='chats')
    op.alter_column('chats', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chats', 'workspace_id')
    # ### end Alembic commands ###
