"""rename file_path to file_url

Revision ID: 8da18c281d08
Revises: 056741f0eee8
Create Date: 2026-05-05 11:40:48.146254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8da18c281d08'
down_revision: Union[str, Sequence[str], None] = '056741f0eee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_url')
    # ### end Alembic commands ###
