"""replace content with ui_message jsonb on messages

Revision ID: acfbfcd76860
Revises: e5329722cfcf
Create Date: 2026-05-10 14:02:34.822051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acfbfcd76860'
down_revision: Union[str, Sequence[str], None] = 'e5329722cfcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ui_message', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'ui_message')
    # ### end Alembic commands ###
