"""remove workspace link between docs

Revision ID: cee2ed1feb21
Revises: 38d4b52b4e95
Create Date: 2026-06-07 10:45:24.676517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee2ed1feb21'
down_revision: Union[str, Sequence[str], None] = '38d4b52b4e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_constraint(op.f('documents_workspace_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_workspace_id_fkey'), 'documents', 'workspace', ['workspace_id'], ['id'])
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
