"""add status to messages table

Revision ID: e5329722cfcf
Revises: b60ed4221ddc
Create Date: 2026-05-07 12:03:59.899340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5329722cfcf'
down_revision: Union[str, Sequence[str], None] = 'b60ed4221ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

message_status_enum = sa.Enum(
    "PENDING",
    "STREAMING",
    "COMPLETED",
    "FAILED",
    name="messagestatus",
)

def upgrade() -> None:
    """Upgrade schema."""
    message_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', message_status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
